accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name='accounts'
urlpatterns=[
	path('signup/',views.SignUpView.as_view(),name='signup'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	url(r'^logout_view/$',views.logout_view,name='logout_view'),
]

myapp/urls.py
from django.conf.urls import url
from . import views

# appname宣言
app_name="myapp"
urlpatterns=[
	url(r'^$',views.index,name='index'),
	url(r'^reg_title/$',views.reg_title,name='reg_title'),
	url(r'^reg_book/$',views.reg_book,name='reg_book'),
	url(r'^ls_title/$',views.ls_title,name='ls_title'),
	url(r'^ls_book/$',views.ls_book,name='ls_book'),
	url(r'^ls_lend/$',views.ls_lend,name='ls_lend'),
#funo
	url(r'^list_user/$',views.list_user,name='list_user'),
	url(r'^return_book/$',views.return_book,name='return_book'),
	url(r'^sub_return_book/$',views.sub_return_book,name='sub_return_book'),
	url(r'^lend_book/$',views.lend_book,name='lend_book'),
	url(r'^return_book/$',views.return_book,name='return_book'),
]

mylib/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/',include('myapp.urls',namespace='myapp')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
]

myapp/forms.py
from django import forms

DEPT_CHOICES=(
	(10,"工学部"),
	(20,"教育学部"),
	(99,"管理課")
)

class Book_reg(forms.Form):
	Book_name=forms.CharField(
		label="本の名前",
		max_length=30,
		required=True,
		widget=forms.TextInput()
	)
class Title_reg(forms.Form):
	Title_name=forms.CharField(
		label="本のタイトル",
		max_length=50,
		required=True,
		widget=forms.TextInput()
	)
	Title_ISBN=forms.CharField(
		label="ISBNなど",
		max_length=30,
		required=True,
		widget=forms.TextInput()
	)

class User_reg(forms.Form):
	User_name=forms.CharField(
		label="氏名",
		max_length=20,
		required=True,
		widget=forms.TextInput()
	)
	User_ID=forms.CharField(
		label="ID",
		max_length=10,
		required=True,
		widget=forms.TextInput()
	)
	Dept_code=forms.ChoiceField(
		label="部局",
		required=True,
		widget=forms.Select,
		choices=DEPT_CHOICES
	)
#funo

class User_id(forms.Form):
	User_ID=forms.CharField(
		label="ID",
		max_length=10,
		required=True,
		widget=forms.TextInput()
	)

# class Lend_reg(forms.Form):
# 	Book_name=forms.CharField(
# 		label="本の名前",
# 		max_length=30,
# 		required=True,
# 		widget=forms.TextInput()
# 	)
# 	User_ID=forms.CharField(
# 		label="ID",
# 		max_length=10,
# 		required=True,
# 		widget=forms.TextInput()
# 	)

class Lend_reg(forms.Form):

	Book_ID=forms.IntegerField(
		label="本のID",
		required=True,
		widget=forms.TextInput()
	)

	User_ID=forms.CharField(
		label="ユーザー名",
		required=False,
		widget=forms.TextInput()
	)

class Return_reg(forms.Form):
	Lend_ID=forms.IntegerField(
		label="貸出ID",
		required=True,
		widget=forms.TextInput()
	)

class Review_form(forms.Form):
	SCORE_CHOICES=(
		(None,"無回答"),
		(1,"おすすめしない"),
		(2,"あまりおすすめしない"),
		(3,"どちらでもない"),
		(4,"おすすめする"),
		(5,"強くおすすめする"),
	)
	Review_score=forms.ChoiceField(
		label="評価",
		required=False,
		choices=SCORE_CHOICES,
		widget=forms.Select
	)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/base.css' %}">
{% block style %}
{% endblock %}
	<meta charset="UTF-8">
	<title>
		{%block title%}
		{%endblock%}
	</title>
</head>
<body>
	<header>
		<div id='header_title'>
			<span id='title'>蔵書管理システム（ZKS)</span>
			{% if user.username %}
				<span id='now_login'>ログイン中:{{ user.username }}</span>
			{% endif %}
		</div>
		<div id='header_index'>
			<div class='index_contents'>
				<label for='label1'>ページ一覧</label>
				<input type="checkbox" id='label1'>
				<div class='hidden_box'>
					<li class='index_link'> <a href="{% url 'myapp:index' %}">ホーム</a><br> </li>
					<li class='index_link'><a href="{% url 'myapp:ls_title' %}">タイトル一覧</a><br></li>
					<li class='index_link'><a href="{% url 'myapp:ls_book' %}">本の一覧</a><br></li>
					<li class='index_link'><a href="{% url 'myapp:lend_book' %}">本の貸し出し</a><br></li>
					<li class='index_link'><a href="{% url 'myapp:ls_lend' %}">未返却一覧</a><br></li>
					{% if user.is_staff %}
						<li class='index_link'><a href="{% url 'myapp:reg_title' %}">タイトル登録</a><br></li>
						<li class='index_link'><a href="{% url 'myapp:list_user' %}">ユーザー一覧</a><br></li>
						<li class='index_link'><a href="{% url 'myapp:return_book' %}">本の返却</a><br></li>
						<li class='index_link'><a href="{% url 'accounts:signup' %}">ユーザー登録</a><br></li>
					{% endif %}
				</div>
			</div>
			<div class='index_contents'>
				{% if user.username %}
					<div id='logout'><a href="{% url 'accounts:logout' %}">ログアウト</a></div>
				{% else %}
					<div id='login'><a href="{% url 'login' %}">ログイン</a></div>
				{% endif %}
			</div>
		</div>
	</header>
{%block body%}
{%endblock%}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/index.css' %}">
{% endblock %}

{% block title %}
目次
{% endblock %}

{% block body %}
<div class='main'>

    <h1>機能一覧</h1>
    <div class="main_contents">
        <a class='btn' href="{% url 'myapp:ls_title' %}">タイトル一覧</a><br>
        <a class='btn' href="{% url 'myapp:ls_book' %}">本の一覧</a><br>
		<a class='btn' href="{% url 'myapp:lend_book' %}">本の貸し出し</a><br>
		<a class='btn' href="{% url 'myapp:ls_lend' %}">未返却一覧</a><br>
        {% if user.is_staff %}
            <a class='btn' href="{% url 'myapp:reg_title' %}">タイトル登録</a><br>
            <a class='btn' href="{% url 'myapp:list_user' %}">ユーザー一覧</a><br>
            <a class='btn' href="{% url 'myapp:return_book' %}">本の返却</a><br>
            <a class='btn' href="{% url 'accounts:signup' %}">ユーザー登録</a><br>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/lend_book.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/Lend_book.css' %}">
{% endblock %}

{% block title %}
本の貸し出し
{% endblock %}

{% block body %}
<div class='main'>
     <h1>本の貸し出し</h1>
    <div class="main_contents">
        <h2>貸し出し</h2>
        <div id='submit_form'>
            <form action="" method="POST">
                {{ form.errors.Book_ID }}
                {% if user.is_staff %}
                    <label id='adjust'>{{ form.User_ID.label }} {{ form.User_ID }}</label><br>
                {% endif %}
                <label >{{ form.Book_ID.label }} {{ form.Book_ID }}</label><br>
                <input id='send' type="submit" value="送信">
                {% csrf_token %}
            </form>
            {% if message %}
                {{ message }}<br>

            {% endif %}
        </div>

        <h2>一覧</h2>
        <table class="lend">

            <tr>
                <th>番号</th>
                <th>本のタイトル</th>
                <th>ユーザー名</th>
                <th>貸し出し日時</th>
                <th>返却日時</th>
            </tr>

            {% for dat in lend_qs %}
                <tr>
                    {% if user.is_staff %}
                        <td>{{ dat.id }}</td>
                        <td>{{ dat.Lend_book.Book_ISBN.Title_name }}</td>
                        <td>{{ dat.Lend_user.username }}</td>
                        <td>{{ dat.Lend_date }}</td>
                        {% if dat.Return_date %}
                            <td>{{ dat.Return_date }}</td>
                        {% else %}
                            <td>未返却</td>
                        {% endif %}
                    {% else %}
                        {% if dat.Lend_user.username == user.username %}
                            <td>{{ dat.id }}</td>
                            <td>{{ dat.Lend_book.Book_ISBN.Title_name }}</td>
                            <td>{{ dat.Lend_user.username }}</td>
                            <td>{{ dat.Lend_date }}</td>
                            {% if dat.Return_date %}
                                <td>{{ dat.Return_date }}</td>
                            {% else %}
                                <td>未返却</td>
                            {% endif %}
                        {% endif %}
                    {% endif %}

                </tr>
            {% endfor %}

        </table>
    </div>
</div>
{% endblock %}

templates/list_user.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/list_user.css' %}">
{% endblock %}

{% block title %}
ユーザーの一覧
{% endblock %}

{% block body %}
<div class='main'>
    <h1>ユーザーの一覧</h1>
    <div class="main_contents">
        {{ message }}
        <table>
        <tr>
            <th>番号</th>
            <th>名前</th>
            <th>ユーザー名</th>
            <th>管理者</th>
            <th></th>
        </tr>
        {% for dat in user_qs %}
        <form  action="" method="POST">
            <tr>
                <td>{{ dat.id }}</td>
                <td>{{ dat.last_name }} {{ dat.first_name }}</td>
                <td>{{ dat.username }}</td>
                <td>{{ dat.is_staff }}</td>
                <td><button name='User_ID' value='{{ dat.id }}' type='submit'>削除</button></td>
            </tr>
            {% csrf_token %}
        </form>


        {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

templates/ls_book.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/ls_book.css' %}">
{% endblock %}
{% block title %}
本の一覧
{% endblock %}

{% block body %}
<div class='main'>
	<h1>本の一覧</h1>
	<div class="main_contents">
		<form action="" name="ls" method="GET">
			<table>
			<tr>
				<th>番号</th>
				<th>本の名前</th>
				<th>ISBNなど</th>
			</tr>
			{% for dat in book_qs %}
			<tr>
				<td>{{ dat.id }}</td>
				<td>{{ dat.Book_ISBN.Title_name }}</td>
				<td>{{ dat.Book_ISBN.Title_ISBN}}</td>
			</tr>

			{% endfor %}
			</table>
			{% csrf_token %}
		</form>
	</div>
</div>
{% endblock %}

templates/ls_lend.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/ls_lend.css' %}">
{% endblock %}

{% block title %}
未返却一覧
{% endblock %}
{% block body %}
<div class='main'>
    <h1>未返却一覧</h1>
    <div class='main_contents'>
        <h2>一覧</h2><hr>
        <table>

            <tr>
                <th>番号</th>
                <th>本</th>
                <th>ユーザー名</th>
                <th>貸し出し日時</th>
            </tr>

            {% for dat in lend_qs %}
                <tr>
                    <td>{{ dat.id }}</td>
                    <td>{{ dat.Lend_book.Book_ISBN.Title_name }}</td>
                    <td>{{ dat.Lend_user.username }}</td>
                    <td>{{ dat.Lend_date }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>
</div>
{% endblock %}

templates/ls_title.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/ls_title.css' %}">
{% endblock %}
{% block title %}
本の一覧
{% endblock %}

{% block body %}
<div class='main'>
	<h1>タイトル一覧</h1>
	<div class="main_contents">
		<form action="" method="post">
				<label ><input type="text" name="title" id=""></label>
				<button value='検索' type='submit'>検索</button>
				{% csrf_token %}
		</form>
		<br>
		<form action="{% url 'myapp:reg_book' %}" name="ls" method="POST">
			<table>
			<tr>
				<th>番号</th>
				<th>タイトル</th>
				<th>ISBN</th>
				<th>評価</th>
				{% if user.is_staff %}
					<th></th>
				{% endif %}
			</tr>
			{% for dat in title_qs %}
			<tr>
				<td>{{ dat.id }}</td>
				<td>{{ dat.Title_name }}</td>
				<td>{{ dat.Title_ISBN }}</td>
				{% if dat.ave %}
					<td>{{ dat.ave}}</td>
				{% else %}
					<td>評価なし</td>
				{% endif %}
				{% if user.is_staff %}
					<td><button name='Title_ID' value='{{ dat.id }}' type='submit'>追加</button></td>
				{% endif %}
			</tr>

			{% endfor %}
			</table>
			{% csrf_token %}
		</form>
	</div>
</div>
{% endblock %}

templates/ls_user.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/base.css' %}">
{% endblock %}
{% block title %}
ユーザー一覧
{% endblock %}

{% block body %}
<div class='main'>
	<h1>一覧</h1>
	<div class="main_contents">
		<table>
		<tr>
			<th>番号</th>
			<th>ユーザーID</th>
			<th>名前</th>
			<th>Staff</th>
		</tr>
		{% for dat in user_qs %}
		<tr>
			<td>{{ dat.id }}</td>
			<td>{{ dat.username }}</td>
			<td>{{ dat.last_name }} { dat.first_name }}</td>
			<td>{{ dat.is_staff }}</td>
		</tr>

		{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

templates/reg_book.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/base.css' %}">
{% endblock %}
{% block title %}
本の登録
{% endblock %}

{% block body %}
<div class='main'>
    <h1>本の登録</h1>
    <div class="main_contents">
        <p>{{ title.Book_ISBN.Title_name }} 登録しました。</p>
    </div>
</div>
{% endblock %}

templates/reg_title.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/reg_title.css' %}">
{% endblock %}
{% block title %}
タイトルの登録
{% endblock %}

{% block body %}
<div class='main'>
	<h1>タイトルの登録</h1>
	<div class="main_contents">
		<form action="" method="post">

			{% csrf_token %}
			<div>
				{{ form.errors.Title_name }}
				{{ form.Title_name.label_tag }} <br>
				{{ form.Title_name }}
			</div>
			<div>
				{{ form.errors.Title_ISBN }}<br>
				{{ form.Title_ISBN.label_tag }}<br>
				{{ form.Title_ISBN }}
			</div>
			<div>
				<input id='send' type="submit" value="送信">
			</div>
		</form>
	</div>
</div>

{% endblock %}

templates/reg_user.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/base.css' %}">
{% endblock %}
{% block title %}
ユーザーの登録
{% endblock %}

{% block body %}
<div class='main'>
	<h1>ユーザーの登録</h1>
	<div class="main_contents">
		<h2>登録</h2>
		<form action="" method="post">
			{{ form.errors.User_name }}
			<label >{{ form.User_name.label }} {{ form.User_name }}</label><br>
			{{ form.errors.User_ID }}
			<label >{{ form.User_ID.label }} {{ form.User_ID }}</label><br>
			{{ form.errors.Dept_code }}
			<label >{{ form.Dept_code.label }} {{ form.Dept_code }}</label><br>
			<input type="submit" value="送信">
			{% csrf_token %}
		</form>
		<hr>
		<h2>一覧</h2>
		<table>
		<tr>
			<td>番号</td>
			<td>ユーザー名</td>
			<td>is_staff</td>
		</tr>
		{% for dat in user_qs %}
		<tr>
			<td>{{ dat.id }}</td>
			<td>{{ dat.username }}</td>
			<td>{{ dat.is_staff }}</td>
		</tr>

		{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

templates/return_book.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/return_book.css' %}">
{% endblock %}

{% block title %}
本の返却
{% endblock %}

{% block body %}
<div class='main'>
    <h1>本の返却</h1>
    <div class="main_contents">
        <div id='submit-form'>
            <form method="post" action="">
                {% csrf_token %}
                <!-- <h3>ユーザーID </h3> -->
                <!-- <input type="text" name="userid_box" id="" required><br> -->
                <label id='adjust'>貸出ID
                <input type="text" name="lendid_box" id="id_Lend_ID" required></label><br>
                <label >{{ form.Review_score.label }} {{ form.Review_score }}</label><br>
                <input id='send' type="submit" value="返却">
            </form>
        </div><br>

        <div id='message'>
            {% if username %}
                返却手続きが完了しました。<br>
                ユーザー:{{ username }}<br>
                タイトル:{{ title }}<br>
            {% endif %}

            {% if message %}
                {{ message }}
            {% endif %}
        </div>

        <h2>一覧</h2><hr>
        <table>

            <tr>
                <th>番号</th>
                <th>本</th>
                <th>ユーザー名</th>
                <th>貸し出し日時</th>
            </tr>

            {% for dat in lend_qs %}
                <tr>
                    <td>{{ dat.id }}</td>
                    <td>{{ dat.Lend_book.Book_ISBN.Title_name }}</td>
                    <td>{{ dat.Lend_user.username }}</td>
                    <td>{{ dat.Lend_date }}</td>
                </tr>
            {% endfor %}

        </table>

    </div>
</div>

{% endblock %}

templates/sub_return_book.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/return_book.css' %}">
{% endblock %}

{% block title %}
本の返却
{% endblock %}

{% block body %}
<div class='main'>
    <h1>本の返却</h1>
    <div class="main_contents">
        <div id='submit-form'>
            <form method="post" action="">
                {% csrf_token %}
                <!-- <h3>ユーザーID </h3> -->
                <!-- <input type="text" name="userid_box" id="" required><br> -->
                <label id='adjust'>貸出ID
                <input type="text" name="lendid_box" id="id_Lend_ID" required></label><br>
                <label >{{ form.Review_score.label }} {{ form.Review_score }}</label><br>
                <input id='send' type="submit" value="返却">
                <input type="hidden" name="User_ID" value="{{ User_ID }}" />
            </form>
        </div><br>

        <div id='message'>
            {% if username %}
                返却手続きが完了しました。<br>
                ユーザー:{{ username }}<br>
                タイトル:{{ title }}<br>
            {% endif %}

            {% if message %}
                {{ message }}
            {% endif %}
        </div>

        <h2>一覧</h2><hr>
        <table>

            <tr>
                <th>番号</th>
                <th>本</th>
                <th>ユーザー名</th>
                <th>貸し出し日時</th>
            </tr>
            {% for dat in lend_qs %}
                <tr>
                    {% if User_ID == dat.id %}
                        <td>{{ dat.id }}</td>
                        <td>{{ dat.Lend_book.Book_ISBN.Title_name }}</td>
                        <td>{{ dat.Lend_user.username }}</td>
                        <td>{{ dat.Lend_date }}</td>
                    {% endif %}
                </tr>
            {% endfor %}

        </table>

    </div>
</div>

{% endblock %}

templates/test_reg_lend.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'myapp/base.css' %}">
{% endblock %}
{% block title %}
テスト:貸し出し登録
{% endblock %}

{% block body %}
<div class='main'>
	<h1>貸し出し登録</h1>
	<div class="main_contents">
		<h2>登録</h2>
		<form action="" method="post">
			{{ form.errors.User_name }}
			<label >{{ form.User_name.label }} {{ form.User_name }}</label><br>
			{{ form.errors.User_ID }}
			<label >{{ form.User_ID.label }} {{ form.User_ID }}</label><br>
			{{ form.errors.Dept_code }}
			<label >{{ form.Dept_code.label }} {{ form.Dept_code }}</label><br>
			<input type="submit" value="送信">
			{% csrf_token %}
		</form>
		<hr>
		<h2>一覧</h2>
		<table>
		<tr>
			<td>番号</td>
			<td>名前</td>
			<td>ユーザーID</td>
			<td>部局コード</td>
		</tr>
		{% for dat in user_qs %}
		<tr>
			<td>{{ dat.id }}</td>
			<td>{{ dat.User_name }}</td>
			<td>{{ dat.User_ID }}</td>
			<td>{{ dat.Dept_code }}</td>
		</tr>

		{% endfor %}
		</table>
	</div>
</div>
{% endblock %}